### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by OmgImAlexis** [nimmis/docker-spigot#12]
```
*** Log: Rebuilding Forked projects....
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'upstream/upstream': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Resolve operation not in progress, we are not resuming.
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open /minecraft/build/Spigot/-Patches/*.patch: No such file
Error compiling Spigot. Please check the wiki for FAQs.
If this does not resolve your issue then please pastebin the entire BuildTools.log.txt file when seeking support.
java.lang.RuntimeException: Error running command, return status !=0: [/bin/sh, applyPatches.sh]
	at org.spigotmc.builder.Builder.runProcess(Builder.java:552)
	at org.spigotmc.builder.Builder.main(Builder.java:434)
cp: cannot stat '//minecraft/build/Spigot/Spigot-Server/target/spigot-*.jar': No such file or directory
*** Log: Resetting  to ...
*** Log: error: Could not remove config section 'remote.upstream'
*** Log:   Applying patches to ...
*** Log:   Something did not apply cleanly to .
*** Log:   Please review above details and finish the apply then
*** Log:   save the changes with rebuildPatches.sh
*** Running /etc/my_runalways/eula...
*** Running /etc/rc.local...
*** Booting supervisor daemon...
*** Supervisor started as PID 486
2016-12-02 04:33:41,481 CRIT Set uid to user 0
*** Started processes via Supervisor......
crond                            RUNNING    pid 490, uptime 0:00:04
spigot                           BACKOFF    Exited too quickly (process log may have details)
syslog-ng                        RUNNING    pid 489, uptime 0:00:04
```

**Comment by nimmis** [comment]
I have fixed the problem, just do a

docker pull nimmis/spigot

to get the newest version, please give me some feedback so I know that it solved you problem

**Comment by OmgImAlexis** [comment]
Looks like it's working. I did get `fatal: $HOME not set` but that didn't seem to affect it at all.

I'm guessing this was meant to download the latest spigot build instead of the craftbukkit one?
```
*** Log: Success! Everything compiled successfully. Copying final .jar files now.
*** Log: Copying craftbukkit-1.11-R0.1-SNAPSHOT.jar to /minecraft/build/.
*** Log:   - Saved as craftbukkit-1.11.jar
*** Log: Copying spigot-1.11-R0.1-SNAPSHOT.jar to /minecraft/build/.
*** Log:   - Saved as spigot-1.11.jar
```

**Comment by nimmis** [comment]
"fatal: $HOME not set" fixed in the latest build
